### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by ericHopkins6** [KLupa/Lupa_CSCI2270_FinalProject#2]
The code compiles and initially looks very good.  However, a few key things started to fall apart when I ran it.
First, there are extra "getline" statements which isn't a big issue, but can make it tedious for the user to retype everything twice.
Next, when I added a city, a lot of the other city districts were messed up.
Lastly, the overall infestation seemed to be completely separate from the individual infestations of the districts (I always received the number 345786)

**Comment by KLupa** [comment]
Thank you
